version: '3.8'

services:
  admin-panel:
    build:
      context: ./admin-panel
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8085:8080"
    restart: unless-stopped
